name: Build STL
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile
      run: |
              make USE_DOCKER=Yes all blank.stl
              mkdir -p lids
              mv *.stl lids

    - uses: actions/upload-artifact@v1
      with:
        name: stl
        path: lids

    - name: Create GitHub Gist
      if: github.ref == 'refs/heads/main'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        for stl in lids/{blank,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday}.stl; do
          gh gist edit 301d97648008bfb42f4573cb1a5ee3b4 -a "$stl"
        done
