name: Build STL
on: [push, pull_request]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: |
              make USE_DOCKER=Yes all blank.stl
              mkdir -p lids
              mv *.stl lids

    - uses: actions/upload-artifact@v4
      with:
        name: stl-docker
        path: lids
        if-no-files-found: error

  build-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install OpenSCAD
      run: |
        sudo apt-get update
        sudo apt-get install openscad

    - name: Compile
      run: |
              make all blank.stl
              mkdir -p lids
              mv *.stl lids

    - uses: actions/upload-artifact@v4
      with:
        name: stl-native
        path: lids
        if-no-files-found: error
