name: Build STL
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: |
              make USE_DOCKER=Yes all blank.stl
              mkdir -p lids
              mv *.stl lids

    - uses: actions/upload-artifact@v4
      with:
        name: stl
        path: lids
        if-no-files-found: error
